// Code generated by "stringer -type=IntepreterType"; DO NOT EDIT

package scaffolt

import "fmt"

const _IntepreterType_name = "JavascriptLua"

var _IntepreterType_index = [...]uint8{0, 10, 13}

func (i IntepreterType) String() string {
	if i < 0 || i >= IntepreterType(len(_IntepreterType_index)-1) {
		return fmt.Sprintf("IntepreterType(%d)", i)
	}
	return _IntepreterType_name[_IntepreterType_index[i]:_IntepreterType_index[i+1]]
}
